// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPidsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CgroupPath    string                 `protobuf:"bytes,1,opt,name=CgroupPath,proto3" json:"CgroupPath,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPidsRequest) Reset() {
	*x = GetPidsRequest{}
	mi := &file_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPidsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPidsRequest) ProtoMessage() {}

func (x *GetPidsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPidsRequest.ProtoReflect.Descriptor instead.
func (*GetPidsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

func (x *GetPidsRequest) GetCgroupPath() string {
	if x != nil {
		return x.CgroupPath
	}
	return ""
}

type GetPidsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EncodedPids   string                 `protobuf:"bytes,1,opt,name=EncodedPids,proto3" json:"EncodedPids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPidsResponse) Reset() {
	*x = GetPidsResponse{}
	mi := &file_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPidsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPidsResponse) ProtoMessage() {}

func (x *GetPidsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPidsResponse.ProtoReflect.Descriptor instead.
func (*GetPidsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1}
}

func (x *GetPidsResponse) GetEncodedPids() string {
	if x != nil {
		return x.EncodedPids
	}
	return ""
}

type GetAllVxpuInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Period        string                 `protobuf:"bytes,1,opt,name=Period,proto3" json:"Period,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllVxpuInfoRequest) Reset() {
	*x = GetAllVxpuInfoRequest{}
	mi := &file_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllVxpuInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllVxpuInfoRequest) ProtoMessage() {}

func (x *GetAllVxpuInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllVxpuInfoRequest.ProtoReflect.Descriptor instead.
func (*GetAllVxpuInfoRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{2}
}

func (x *GetAllVxpuInfoRequest) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

type GetAllVxpuInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VxpuInfos     string                 `protobuf:"bytes,1,opt,name=VxpuInfos,proto3" json:"VxpuInfos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllVxpuInfoResponse) Reset() {
	*x = GetAllVxpuInfoResponse{}
	mi := &file_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllVxpuInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllVxpuInfoResponse) ProtoMessage() {}

func (x *GetAllVxpuInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllVxpuInfoResponse.ProtoReflect.Descriptor instead.
func (*GetAllVxpuInfoResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{3}
}

func (x *GetAllVxpuInfoResponse) GetVxpuInfos() string {
	if x != nil {
		return x.VxpuInfos
	}
	return ""
}

var File_api_proto protoreflect.FileDescriptor

const file_api_proto_rawDesc = "" +
	"\n" +
	"\tapi.proto\"0\n" +
	"\x0eGetPidsRequest\x12\x1e\n" +
	"\n" +
	"CgroupPath\x18\x01 \x01(\tR\n" +
	"CgroupPath\"3\n" +
	"\x0fGetPidsResponse\x12 \n" +
	"\vEncodedPids\x18\x01 \x01(\tR\vEncodedPids\"/\n" +
	"\x15GetAllVxpuInfoRequest\x12\x16\n" +
	"\x06Period\x18\x01 \x01(\tR\x06Period\"6\n" +
	"\x16GetAllVxpuInfoResponse\x12\x1c\n" +
	"\tVxpuInfos\x18\x01 \x01(\tR\tVxpuInfos2\x82\x01\n" +
	"\vPidsService\x12.\n" +
	"\aGetPids\x12\x0f.GetPidsRequest\x1a\x10.GetPidsResponse\"\x00\x12C\n" +
	"\x0eGetAllVxpuInfo\x12\x16.GetAllVxpuInfoRequest\x1a\x17.GetAllVxpuInfoResponse\"\x00B\fZ\n" +
	"./;serviceb\x06proto3"

var (
	file_api_proto_rawDescOnce sync.Once
	file_api_proto_rawDescData []byte
)

func file_api_proto_rawDescGZIP() []byte {
	file_api_proto_rawDescOnce.Do(func() {
		file_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)))
	})
	return file_api_proto_rawDescData
}

var file_api_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_proto_goTypes = []any{
	(*GetPidsRequest)(nil),         // 0: GetPidsRequest
	(*GetPidsResponse)(nil),        // 1: GetPidsResponse
	(*GetAllVxpuInfoRequest)(nil),  // 2: GetAllVxpuInfoRequest
	(*GetAllVxpuInfoResponse)(nil), // 3: GetAllVxpuInfoResponse
}
var file_api_proto_depIdxs = []int32{
	0, // 0: PidsService.GetPids:input_type -> GetPidsRequest
	2, // 1: PidsService.GetAllVxpuInfo:input_type -> GetAllVxpuInfoRequest
	1, // 2: PidsService.GetPids:output_type -> GetPidsResponse
	3, // 3: PidsService.GetAllVxpuInfo:output_type -> GetAllVxpuInfoResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_init() }
func file_api_proto_init() {
	if File_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_goTypes,
		DependencyIndexes: file_api_proto_depIdxs,
		MessageInfos:      file_api_proto_msgTypes,
	}.Build()
	File_api_proto = out.File
	file_api_proto_goTypes = nil
	file_api_proto_depIdxs = nil
}
