/*
Copyright (c) Huawei Technologies Co., Ltd. 2024-2024. All rights reserved.
*/

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// 	protoc-gen-go-grpc v1.2.0
// 	protoc              v3.14.0
// source: api.proto

package service

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

const (
	PidsService_GetPids_FullMethodName       = "/service.PidsService/GetPids"
	PidsService_GetAllVgpuInfo_FullMethodName = "/service.PidsService/GetAllVgpuInfo"
)

// PidsServiceClient is the client API for PidsService service.
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc#ClientConn.NewStream.
type PidsServiceClient interface {
	GetPids(ctx context.Context, in *GetPidsRequest, opts ...grpc.CallOption) (*GetPidsResponse, error)
	GetAllVgpuInfo(ctx context.Context, in *GetAllVgpuInfoRequest, opts ...grpc.CallOption) (*GetAllVgpuInfoResponse, error)
}

type pidsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPidsServiceClient(cc grpc.ClientConnInterface) PidsServiceClient {
	return &pidsServiceClient{cc}
}

func (c *pidsServiceClient) GetPids(ctx context.Context, in *GetPidsRequest, opts ...grpc.CallOption) (*GetPidsResponse, error) {
	out := new(GetPidsResponse)
	err := c.cc.Invoke(ctx, PidsService_GetPids_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pidsServiceClient) GetAllVgpuInfo(ctx context.Context, in *GetAllVgpuInfoRequest, opts ...grpc.CallOption) (*GetAllVgpuInfoResponse, error) {
	out := new(GetAllVgpuInfoResponse)
	err := c.cc.Invoke(ctx, PidsService_GetAllVgpuInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PidsServiceServer is the server API for PidsService service.
// All implementations must embed UnimplementedPidsServiceServer
// for forward compatibility.
type PidsServiceServer interface {
	GetPids(context.Context, *GetPidsRequest) (*GetPidsResponse, error)
	GetAllVgpuInfo(context.Context, *GetAllVgpuInfoRequest) (*GetAllVgpuInfoResponse, error)
	mustEmbedUnimplementedPidsServiceServer()
}

// UnimplementedPidsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPidsServiceServer struct {
}

func (UnimplementedPidsServiceServer) GetPids(context.Context, *GetPidsRequest) (*GetPidsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPids not implemented")
}
func (UnimplementedPidsServiceServer) GetAllVgpuInfo(context.Context, *GetAllVgpuInfoRequest) (*GetAllVgpuInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllVgpuInfo not implemented")
}
func (UnimplementedPidsServiceServer) mustEmbedUnimplementedPidsServiceServer() {}

// UnsafePidsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PidsServiceServer will
// result in compilation errors.
type UnsafePidsServiceServer interface {
	mustEmbedUnimplementedPidsServiceServer()
}

func RegisterPidsServiceServer(s grpc.ServiceRegistrar, srv PidsServiceServer) {
	s.RegisterService(&PidsService_ServiceDesc, srv)
}

func _PidsService_GetPids_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPidsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PidsServiceServer).GetPids(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PidsService_GetPids_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PidsServiceServer).GetPids(ctx, req.(*GetPidsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PidsService_GetAllVgpuInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllVgpuInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PidsServiceServer).GetAllVgpuInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PidsService_GetAllVgpuInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PidsServiceServer).GetAllVgpuInfo(ctx, req.(*GetAllVgpuInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PidsService_ServiceDesc is the grpc.ServiceDesc for PidsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy).
var PidsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.PidsService",
	HandlerType: (*PidsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPids",
			Handler:    _PidsService_GetPids_Handler,
		},
		{
			MethodName: "GetAllVgpuInfo",
			Handler:    _PidsService_GetAllVgpuInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}